spring.application.name=BackEnd

spring.config.import=optional:application-secret.properties

jwt.expiration=60000
jwt.refresh=300000

# server
server.port=${SERVER_PORT:8080}
server.max-http-request-header-size=65536

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=6000

# swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

#docker start c57d0e3c1d8c